CREATE TABLE  "TN_USER_INFO" 
   (	"USER_IDX" NUMBER(13,0) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(64), 
	"USER_NAME" VARCHAR2(64), 
	"USER_EMAIL" VARCHAR2(128) NOT NULL ENABLE, 
	"USER_ADDR" VARCHAR2(128), 
	"PHONE" VARCHAR2(32), 
	"CRT_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"USER_ROLE" CHAR(1) DEFAULT 'U' NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(256) NOT NULL ENABLE, 
	 CONSTRAINT "TN_USER_INFO_PK" PRIMARY KEY ("USER_IDX") ENABLE, 
	 CONSTRAINT "TN_USER_INFO_U01" UNIQUE ("USER_ID") ENABLE, 
	 CONSTRAINT "TN_USER_INFO_U02" UNIQUE ("USER_EMAIL") ENABLE
   )
;
CREATE TABLE  "TN_COMMENT" 
   (	"COMMENT_ID" NUMBER(13,0) DEFAULT 0 NOT NULL ENABLE, 
	"USER_IDX" NUMBER(13,0) NOT NULL ENABLE, 
	"IP_ADDR" VARCHAR2(22) NOT NULL ENABLE, 
	"BODY" VARCHAR2(512) NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"UPD_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "TN_COMMENT_PK" PRIMARY KEY ("COMMENT_ID") ENABLE, 
	 CONSTRAINT "TN_COMMENT_R01" FOREIGN KEY ("USER_IDX")
	  REFERENCES  "TN_USER_INFO" ("USER_IDX") ENABLE
   )
;
CREATE TABLE  "TN_CONTENT" 
   (	"CONTENT_ID" NUMBER(13,0) DEFAULT 0 NOT NULL ENABLE, 
	"TITLE" VARCHAR2(256) DEFAULT 'NO TITLE' NOT NULL ENABLE, 
	"USER_IDX" NUMBER(13,0) NOT NULL ENABLE, 
	"IP_ADDR" VARCHAR2(22) NOT NULL ENABLE, 
	"VIEW_COUNT" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"REC_COUNT" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CONTENT_TYPE" CHAR(1) DEFAULT 'D' NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"UPD_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "TN_CONTENT_PK" PRIMARY KEY ("CONTENT_ID") ENABLE, 
	 CONSTRAINT "TN_CONTENT_R01" FOREIGN KEY ("USER_IDX")
	  REFERENCES  "TN_USER_INFO" ("USER_IDX") ENABLE
   )
;
CREATE TABLE  "TN_CNT_CMT" 
   (	"CONTENT_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"COMMENT_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"PARENT_COMMENT_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"COMMENT_ORDER" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"UPD_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "TN_CNT_CMT_PK" PRIMARY KEY ("CONTENT_ID", "COMMENT_ID", "PARENT_COMMENT_ID") ENABLE, 
	 CONSTRAINT "TN_CNT_CMT_R01" FOREIGN KEY ("CONTENT_ID")
	  REFERENCES  "TN_CONTENT" ("CONTENT_ID") ENABLE, 
	 CONSTRAINT "TN_CNT_CMT_R02" FOREIGN KEY ("COMMENT_ID")
	  REFERENCES  "TN_COMMENT" ("COMMENT_ID") ENABLE
   )
;

CREATE TABLE  "TN_DIR" 
   (	"DIR_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"PHY_PATH" VARCHAR2(256) NOT NULL ENABLE, 
	"DIR_TYPE" CHAR(1) DEFAULT 'A' NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "TN_DIR_PK" PRIMARY KEY ("DIR_ID") ENABLE, 
	 CONSTRAINT "TN_DIR_U01" UNIQUE ("PHY_PATH") ENABLE
   )
;

CREATE TABLE  "TN_FILE" 
   (	"FILE_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(256) NOT NULL ENABLE, 
	"DIR_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"FILE_SIZE" NUMBER(13,0) DEFAULT 0 NOT NULL ENABLE, 
	"FILE_TYPE" CHAR(1) DEFAULT 'A' NOT NULL ENABLE, 
	"VIEW_COUNT" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"EXTENTION" VARCHAR2(5) NOT NULL ENABLE, 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"PHY_NAME" VARCHAR2(64) NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "TN_FILE_PK" PRIMARY KEY ("FILE_ID") ENABLE, 
	 CONSTRAINT "TN_FILE_R01" FOREIGN KEY ("DIR_ID")
	  REFERENCES  "TN_DIR" ("DIR_ID") ENABLE
   )
;


CREATE TABLE  "TN_CNT_FILE" 
   (	"CONTENT_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"FILE_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"UPD_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "TN_CNT_FILE_PK" PRIMARY KEY ("CONTENT_ID", "FILE_ID") ENABLE, 
	 CONSTRAINT "TN_CNT_FILE_R01" FOREIGN KEY ("CONTENT_ID")
	  REFERENCES  "TN_CONTENT" ("CONTENT_ID") ENABLE, 
	 CONSTRAINT "TN_CNT_FILE_R02" FOREIGN KEY ("FILE_ID")
	  REFERENCES  "TN_FILE" ("FILE_ID") ENABLE
   )
;



CREATE TABLE  "TN_PATH" 
   (	"PATH_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"PATH_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"USER_IDX" NUMBER(13,0) NOT NULL ENABLE, 
	"PATH_ORDER" NUMBER(4,0) NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"UPD_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "TN_PATH_PK" PRIMARY KEY ("PATH_ID") ENABLE
   )
;
CREATE TABLE  "TN_CNT_PATH" 
   (	"CONTENT_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"PATH_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"USER_IDX" NUMBER(13,0) NOT NULL ENABLE, 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"UPD_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "TN_CNT_PATH_PK" PRIMARY KEY ("CONTENT_ID", "PATH_ID", "USER_IDX") ENABLE, 
	 CONSTRAINT "TN_CNT_PATH_R01" FOREIGN KEY ("PATH_ID")
	  REFERENCES  "TN_PATH" ("PATH_ID") ENABLE
   )
;
CREATE TABLE  "TN_TAG" 
   (	"TAG_ID" NUMBER(13,0) DEFAULT 0 NOT NULL ENABLE, 
	"TAG_NAME" VARCHAR2(128) DEFAULT '' NOT NULL ENABLE, 
	"TAG_COUNT" NUMBER(10,0) DEFAULT 1 NOT NULL ENABLE, 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"UPD_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "TN_TAG_PK" PRIMARY KEY ("TAG_ID") ENABLE, 
	 UNIQUE ("TAG_NAME") ENABLE
   )
;
CREATE TABLE  "TN_CNT_TAG" 
   (	"CONTENT_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"TAG_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate, 
	 CONSTRAINT "TN_CNT_TAG_PK" PRIMARY KEY ("CONTENT_ID", "TAG_ID") ENABLE, 
	 CONSTRAINT "TN_CNT_TAG_R01" FOREIGN KEY ("CONTENT_ID")
	  REFERENCES  "TN_CONTENT" ("CONTENT_ID") ENABLE, 
	 CONSTRAINT "TN_CNT_TAG_R02" FOREIGN KEY ("TAG_ID")
	  REFERENCES  "TN_TAG" ("TAG_ID") ENABLE
   )
;

CREATE TABLE  "TN_DOCUMENT" 
   (	"CONTENT_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"BODY" CLOB NOT NULL ENABLE, 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate, 
	"UPD_TIME" DATE DEFAULT sysdate, 
	 CONSTRAINT "TN_DOCUMENT_PK" PRIMARY KEY ("CONTENT_ID") ENABLE, 
	 CONSTRAINT "TN_DOCUMENT_R01" FOREIGN KEY ("CONTENT_ID")
	  REFERENCES  "TN_CONTENT" ("CONTENT_ID") ENABLE
   )
;
CREATE TABLE  "TN_GROUP" 
   (	"GROUP_ID" NUMBER(10,0), 
	"GROUP_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "TN_GROUP_PK" PRIMARY KEY ("GROUP_ID") ENABLE
   )
;
CREATE TABLE  "TN_GPATH" 
   (	"G_PATH_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"G_PATH_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"GROUP_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"G_PATH_ORDER" NUMBER(4,0) NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) NOT NULL ENABLE, 
	"STATE" NUMBER(1,0) NOT NULL ENABLE, 
	"CRT_TIME" DATE NOT NULL ENABLE, 
	"UPD_TIME" DATE NOT NULL ENABLE, 
	 CONSTRAINT "TN_GPATH_PK" PRIMARY KEY ("G_PATH_ID", "GROUP_ID") ENABLE, 
	 CONSTRAINT "TN_GPATH_R01" FOREIGN KEY ("GROUP_ID")
	  REFERENCES  "TN_GROUP" ("GROUP_ID") ENABLE
   )
;
CREATE TABLE  "TN_GPATH_RELATION" 
   (	"G_PATH_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"GROUP_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"PARENT_G_PATH_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"G_PATH_ORDER" NUMBER(13,0) NOT NULL ENABLE, 
	"RE_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"STATE" NUMBER(1,0) NOT NULL ENABLE, 
	"CRT_TIME" DATE NOT NULL ENABLE, 
	"UPD_TIME" DATE NOT NULL ENABLE, 
	 CONSTRAINT "TN_GPATH_RELATION_PK" PRIMARY KEY ("GROUP_ID", "G_PATH_ID", "PARENT_G_PATH_ID") ENABLE, 
	 CONSTRAINT "TN_GPATH_RELATION_R01" FOREIGN KEY ("GROUP_ID")
	  REFERENCES  "TN_GROUP" ("GROUP_ID") ENABLE, 
	 CONSTRAINT "TN_GPATH_RELATION_R02" FOREIGN KEY ("GROUP_ID", "PARENT_G_PATH_ID")
	  REFERENCES  "TN_GPATH" ("G_PATH_ID", "GROUP_ID") ENABLE
   )
;
CREATE TABLE  "TN_GROUP_PATH" 
   (	"GROUP_ID" NUMBER(13,0), 
	"PATH_ID" NUMBER(10,0), 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"UPD_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"USER_IDX" NUMBER(13,0) NOT NULL ENABLE, 
	 CONSTRAINT "TN_GROUP_PATH_PK" PRIMARY KEY ("GROUP_ID", "PATH_ID") ENABLE, 
	 CONSTRAINT "TN_GROUP_PATH_R01" FOREIGN KEY ("GROUP_ID")
	  REFERENCES  "TN_GROUP" ("GROUP_ID") ENABLE, 
	 CONSTRAINT "TN_GROUP_PATH_R02" FOREIGN KEY ("PATH_ID")
	  REFERENCES  "TN_PATH" ("PATH_ID") ENABLE, 
	 CONSTRAINT "TN_GROUP_PATH_R03" FOREIGN KEY ("USER_IDX")
	  REFERENCES  "TN_USER_INFO" ("USER_IDX") ENABLE
   )
;
CREATE TABLE  "TN_JOB" 
   (	"CONTENT_ID" NUMBER(13,0), 
	"BODY" CLOB, 
	"PAY" NUMBER(7,2) DEFAULT 0.0, 
	"DUE_DATE" VARCHAR2(10) DEFAULT '00;00;0000', 
	"JOB_TYPE" CHAR(2) DEFAULT 'FT', 
	"AD_TYPE" CHAR(1) DEFAULT 'A', 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CRT_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"UPD_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"POS_X" NUMBER(16,10) DEFAULT 0 NOT NULL ENABLE, 
	"POS_Y" NUMBER(16,10) DEFAULT 0 NOT NULL ENABLE, 
	"SUBURB" VARCHAR2(32), 
	"ADDR" VARCHAR2(256), 
	 CONSTRAINT "TN_JOB_PK" PRIMARY KEY ("CONTENT_ID", "JOB_TYPE") ENABLE
   )
;
CREATE TABLE  "TN_MOVIE" 
   (	"CONTENT_ID" NUMBER(13,0), 
	"BODY" VARCHAR2(1024), 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"UPD_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"OPENING_DATE" VARCHAR2(10) DEFAULT '00;00;0000', 
	"CLOSING_DATE" VARCHAR2(10) DEFAULT '00;00;0000', 
	 CONSTRAINT "TN_MOVIE_PK" PRIMARY KEY ("CONTENT_ID") ENABLE, 
	 CONSTRAINT "TN_MOVIE_R01" FOREIGN KEY ("CONTENT_ID")
	  REFERENCES  "TN_CONTENT" ("CONTENT_ID") ENABLE
   )
;
CREATE TABLE  "TN_PATH_RELATION" 
   (	"PATH_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"USER_IDX" NUMBER(13,0) NOT NULL ENABLE, 
	"PARENT_PATH_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"PATH_ORDER" NUMBER(13,0) DEFAULT 0 NOT NULL ENABLE, 
	"RE_NAME" VARCHAR2(128) DEFAULT '' NOT NULL ENABLE, 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"UPD_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "TN_PATH_RELATION_PK" PRIMARY KEY ("PATH_ID", "USER_IDX") ENABLE, 
	 CONSTRAINT "TN_PATH_RELATION_R02" FOREIGN KEY ("USER_IDX")
	  REFERENCES  "TN_USER_INFO" ("USER_IDX") ENABLE
   )
;
CREATE TABLE  "TN_REAL_ESTATE" 
   (	"CONTENT_ID" NUMBER(13,0) NOT NULL ENABLE, 
	"BODY" CLOB NOT NULL ENABLE, 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate, 
	"UPD_TIME" DATE DEFAULT sysdate, 
	"POS_X" NUMBER(16,10) DEFAULT 0, 
	"POS_Y" NUMBER(16,10) DEFAULT 0, 
	"SUBURB" VARCHAR2(32) DEFAULT 'Brisbane', 
	"PRICE" NUMBER(13,2) DEFAULT 0, 
	"ADDR" VARCHAR2(256) DEFAULT '', 
	"ROOM_TYPE" VARCHAR2(32) DEFAULT 'Second Room', 
	"SMOKING" CHAR(1) DEFAULT 'N', 
	"PETS" CHAR(1) DEFAULT 'N', 
	"GENDER" CHAR(1) DEFAULT 'M', 
	"AVAILABLE_DATE" VARCHAR2(10) DEFAULT '00;00;0000', 
	 CONSTRAINT "TN_REAL_ESTATE_U01" UNIQUE ("CONTENT_ID") ENABLE, 
	 CONSTRAINT "TN_REAL_ESTATE_R01" FOREIGN KEY ("CONTENT_ID")
	  REFERENCES  "TN_CONTENT" ("CONTENT_ID") ENABLE
   )
;
CREATE TABLE  "TN_SAMPLE" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(32) NOT NULL ENABLE
   )
;
CREATE TABLE  "TN_TEST" 
   (	"TEST_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(32) NOT NULL ENABLE, 
	 CONSTRAINT "TN_TEST_PK" PRIMARY KEY ("TEST_ID") ENABLE
   )
;
CREATE TABLE  "TN_USER_GROUP" 
   (	"USER_IDX" NUMBER(13,0), 
	"GROUP_ID" NUMBER(10,0), 
	"STATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CRT_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"UPD_TIME" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "TN_USER_GROUP_PK" PRIMARY KEY ("USER_IDX", "GROUP_ID") ENABLE, 
	 CONSTRAINT "TN_USER_GROUP_R01" FOREIGN KEY ("USER_IDX")
	  REFERENCES  "TN_USER_INFO" ("USER_IDX") ENABLE, 
	 CONSTRAINT "TN_USER_GROUP_R02" FOREIGN KEY ("GROUP_ID")
	  REFERENCES  "TN_GROUP" ("GROUP_ID") ENABLE
   )
;
CREATE TABLE  "TN_WATCH" 
   (	"USER_IDX" NUMBER(13,0), 
	"CONTENT_ID" NUMBER(13,0), 
	"DEL_YN" CHAR(1) DEFAULT 'N', 
	"STATUS" NUMBER(1,0) DEFAULT 0, 
	"CRT_TIME" DATE DEFAULT sysdate, 
	 CONSTRAINT "TN_WATCH_PK" PRIMARY KEY ("USER_IDX", "CONTENT_ID") ENABLE, 
	 CONSTRAINT "TN_WATCH_R01" FOREIGN KEY ("USER_IDX")
	  REFERENCES  "TN_USER_INFO" ("USER_IDX") ENABLE, 
	 CONSTRAINT "TN_WATCH_R02" FOREIGN KEY ("CONTENT_ID")
	  REFERENCES  "TN_CONTENT" ("CONTENT_ID") ENABLE
   )
;

CREATE UNIQUE INDEX  "TN_CNT_CMT_PK" ON  "TN_CNT_CMT" ("CONTENT_ID", "COMMENT_ID", "PARENT_COMMENT_ID")
;
CREATE UNIQUE INDEX  "TN_CNT_FILE_PK" ON  "TN_CNT_FILE" ("CONTENT_ID", "FILE_ID")
;
CREATE UNIQUE INDEX  "TN_CNT_PATH_PK" ON  "TN_CNT_PATH" ("CONTENT_ID", "PATH_ID", "USER_IDX")
;
CREATE UNIQUE INDEX  "TN_CNT_TAG_PK" ON  "TN_CNT_TAG" ("CONTENT_ID", "TAG_ID")
;
CREATE UNIQUE INDEX  "TN_COMMENT_PK" ON  "TN_COMMENT" ("COMMENT_ID")
;
CREATE UNIQUE INDEX  "TN_CONTENT_PK" ON  "TN_CONTENT" ("CONTENT_ID")
;
CREATE UNIQUE INDEX  "TN_DIR_PK" ON  "TN_DIR" ("DIR_ID")
;
CREATE UNIQUE INDEX  "TN_DIR_U01" ON  "TN_DIR" ("PHY_PATH")
;
CREATE UNIQUE INDEX  "TN_DOCUMENT_PK" ON  "TN_DOCUMENT" ("CONTENT_ID")
;
CREATE UNIQUE INDEX  "TN_FILE_PK" ON  "TN_FILE" ("FILE_ID")
;
CREATE UNIQUE INDEX  "TN_GPATH_PK" ON  "TN_GPATH" ("G_PATH_ID", "GROUP_ID")
;
CREATE UNIQUE INDEX  "TN_GPATH_RELATION_PK" ON  "TN_GPATH_RELATION" ("GROUP_ID", "G_PATH_ID", "PARENT_G_PATH_ID")
;
CREATE UNIQUE INDEX  "TN_GROUP_PATH_PK" ON  "TN_GROUP_PATH" ("GROUP_ID", "PATH_ID")
;
CREATE UNIQUE INDEX  "TN_GROUP_PK" ON  "TN_GROUP" ("GROUP_ID")
;
CREATE UNIQUE INDEX  "TN_JOB_PK" ON  "TN_JOB" ("CONTENT_ID", "JOB_TYPE")
;
CREATE UNIQUE INDEX  "TN_MOVIE_PK" ON  "TN_MOVIE" ("CONTENT_ID")
;
CREATE UNIQUE INDEX  "TN_PATH_PK" ON  "TN_PATH" ("PATH_ID")
;
CREATE UNIQUE INDEX  "TN_PATH_RELATION_PK" ON  "TN_PATH_RELATION" ("PATH_ID", "USER_IDX")
;
CREATE UNIQUE INDEX  "TN_REAL_ESTATE_U01" ON  "TN_REAL_ESTATE" ("CONTENT_ID")
;
CREATE UNIQUE INDEX  "TN_TAG_PK" ON  "TN_TAG" ("TAG_ID")
;
CREATE UNIQUE INDEX  "TN_TEST_PK" ON  "TN_TEST" ("TEST_ID")
;
CREATE UNIQUE INDEX  "TN_USER_GROUP_PK" ON  "TN_USER_GROUP" ("USER_IDX", "GROUP_ID")
;
CREATE UNIQUE INDEX  "TN_USER_INFO_PK" ON  "TN_USER_INFO" ("USER_IDX")
;
CREATE UNIQUE INDEX  "TN_USER_INFO_U01" ON  "TN_USER_INFO" ("USER_ID")
;
CREATE UNIQUE INDEX  "TN_USER_INFO_U02" ON  "TN_USER_INFO" ("USER_EMAIL")
;
CREATE UNIQUE INDEX  "TN_WATCH_PK" ON  "TN_WATCH" ("USER_IDX", "CONTENT_ID")
;
 CREATE SEQUENCE   "SEQ_TN_COMMENT"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 47 NOCACHE  NOORDER  NOCYCLE
;
 CREATE SEQUENCE   "SEQ_TN_CONTENT"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10137 CACHE 2 NOORDER  NOCYCLE
;
 CREATE SEQUENCE   "SEQ_TN_DIR"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 4008 CACHE 2 NOORDER  NOCYCLE
;
 CREATE SEQUENCE   "SEQ_TN_FILE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 4336 CACHE 2 NOORDER  NOCYCLE
;
 CREATE SEQUENCE   "SEQ_TN_GROUP"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 71 NOCACHE  NOORDER  NOCYCLE
;
 CREATE SEQUENCE   "SEQ_TN_PATH"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 35 NOCACHE  NOORDER  NOCYCLE
;
 CREATE SEQUENCE   "SEQ_TN_TAG"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1001 CACHE 2 NOORDER  NOCYCLE
;
 CREATE SEQUENCE   "SQL_TN_USER_INFO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 18 NOCACHE  NOORDER  NOCYCLE
;
